### ISSUE TITLE
названия аргументов

### ISSUE THREAD

**Issue by kuzmichevdima** [befozg/Game-Life#1]
https://github.com/Karen-1999/Game-Life/blob/f785a71ad68d2ad8ab60b506b6bf5420dd4f607f/main.py#L5-L6

аргумент --input-dir, но подается не директория, файл. --output-dir то же самое

**Comment by befozg** [comment]
Исправил:
input-dir -> input-file и output аналогично. Также называются теперь соответствующие опции
