### ISSUE TITLE
n, m

### ISSUE THREAD

**Issue by kuzmichevdima** [befozg/Game-Life#10]
https://github.com/Karen-1999/Game-Life/blob/f785a71ad68d2ad8ab60b506b6bf5420dd4f607f/myclasses.py#L84-L85

используй просто self.n, self.m. Вообще n и m нужно назвать более адекватно

**Comment by befozg** [comment]
исправил: 
n-> width
m->length

**Comment by kuzmichevdima** [comment]
https://github.com/Karen-1999/Game-Life/blob/c28d0dbeec304d48fa421e57604811035917b80a/model.py#L143-L144
зачем вообще создавать n и m? используй self.width, self.height (length->height)

**Comment by befozg** [comment]
исправил
