### ISSUE TITLE
названия методов

### ISSUE THREAD

**Issue by kuzmichevdima** [befozg/Game-Life#11]
https://github.com/Karen-1999/Game-Life/blob/f785a71ad68d2ad8ab60b506b6bf5420dd4f607f/myclasses.py#L109

названия методов по style guide должны состоять из слов, разделенных подчеркиванием. То есть countnear->count_near. Хотя вообще название малопонятное, "посчитать рядом". Посчитать что конкретно?

**Comment by befozg** [comment]
Исправил название на count_of_neighbors.
