### ISSUE TITLE
final_state

### ISSUE THREAD

**Issue by kuzmichevdima** [befozg/Game-Life#12]
https://github.com/Karen-1999/Game-Life/blob/c28d0dbeec304d48fa421e57604811035917b80a/model.py#L44

я не понимаю во-первых, почему так называется. Во-вторых, почему этот метод копипастится из класса в класс? Такого не должно быть, поскольку логика подсчета (именно подсчета) соседей везде одинакова, а вот уже учет количеств разный

**Comment by befozg** [comment]
Почему одинаковые правила подсчета соседей? у нас же могут добавиться виды животных, для которых надо посчитать там, допустим количество всех соседей, без разбора типов, и тогда у нас вообще невозможно делать как ты требуешь. Или допустим, добавил Fish_1 на который влияет n вида животных других, ведь я должен либо возвращать кортеж с количеством соседей по типам, что не оптимально если n слишком большой, или возвращать сразу по каким то правилам состояние ячейки после прохода. Я же не могу гарантировать, что вы не добавите рыбку с правилами жизни странными.

**Comment by befozg** [comment]
исправил
