### ISSUE TITLE
defaultdict

### ISSUE THREAD

**Issue by kuzmichevdima** [befozg/Game-Life#15]
https://github.com/Karen-1999/Game-Life/blob/2b0e8ce20d7de00693dd63603424e4e6d6372b50/model.py#L26-L29

чтобы не делать лишние проверки, используй defaultdict

**Comment by befozg** [comment]
исправил

**Comment by befozg** [comment]
исправил

**Comment by kuzmichevdima** [comment]
С defaultdict я не понимаю, зачем нужны эти проверки:
https://github.com/Karen-1999/Game-Life/blob/85893f0087304aa3cd890b711e8e22b0f2d26221/model.py#L57-L58

**Comment by befozg** [comment]
исправлено
