### ISSUE TITLE
if __name__ == "__main__"

### ISSUE THREAD

**Issue by kuzmichevdima** [befozg/Game-Life#18]

**Comment by befozg** [comment]
Done

**Comment by kuzmichevdima** [comment]
https://github.com/Karen-1999/Game-Life/blob/195ebd3564c3e58ba403f1f40f5e64f1847e55f4/model.py#L149-L152

Почему этот код лежит вне функций/методов? Он сейчас выполняется просто в момент импорта

**Comment by befozg** [comment]
Done!
