### ISSUE TITLE
сделать универсально

### ISSUE THREAD

**Issue by kuzmichevdima** [befozg/Game-Life#20]
https://github.com/Karen-1999/Game-Life/blob/85893f0087304aa3cd890b711e8e22b0f2d26221/model.py#L164-L169

так делать плохо, потому что каким-то образом при добавлении нового вида нужно догадаться, что нужно добавить сюда еще элемент. Сделай автогенерацию этого словаря, используя  спец аттрибут _ _subclasses_ _ от Animal

**Comment by befozg** [comment]
сделал автогенерацию словаря
