### ISSUE TITLE
n, m, k

### ISSUE THREAD

**Issue by kuzmichevdima** [befozg/Game-Life#3]
https://github.com/Karen-1999/Game-Life/blob/f785a71ad68d2ad8ab60b506b6bf5420dd4f607f/main.py#L18-L20

в одну строчку: n, m, k = list_first_line
нужно придумать названия получше, чем n, m, k. В условии задачи эти параметры так называются для краткости

**Comment by befozg** [comment]
исправлено на n m k -> length width generations соответственно
