### ISSUE TITLE
разбор случаев с копипастом

### ISSUE THREAD

**Issue by kuzmichevdima** [befozg/Game-Life#5]
https://github.com/Karen-1999/Game-Life/blob/f785a71ad68d2ad8ab60b506b6bf5420dd4f607f/myclasses.py#L92-L105

Цель создания классов в том, чтобы работа с ними была одинаковой. То есть у них должен быть какой-то метод, который можно вызвать у любого наследника  Animal одинаковым образом и получить результат, специфичный для этого класса.

**Comment by befozg** [comment]
Исправил. Нет копипаста.
