### ISSUE TITLE
счетчики

### ISSUE THREAD

**Issue by kuzmichevdima** [befozg/Game-Life#6]
https://github.com/Karen-1999/Game-Life/blob/f785a71ad68d2ad8ab60b506b6bf5420dd4f607f/myclasses.py#L116-L129

что, если добавится еще 10 видов животных? Во-первых, countnear придется сильно менять, во-во-вторых, будет возвращаться тапл из огромного числа элементов.

**Comment by befozg** [comment]
сделал гибким , не считая количество соседей отдельно, а написав метод final_state, который берет и по правилам класса просто возвращает тип рыбки, который должен быть записан в ячейку.

**Comment by kuzmichevdima** [comment]
#12

**Comment by befozg** [comment]
исправлено
