### ISSUE TITLE
тесты

### ISSUE THREAD

**Issue by kuzmichevdima** [befozg/Game-Life#8]
https://github.com/Karen-1999/Game-Life/blob/f785a71ad68d2ad8ab60b506b6bf5420dd4f607f/utest_myclasses.py#L10

Тесты проверяют простые вещи, но не проверяют логику изменения поля в целом вообще.

**Comment by befozg** [comment]
написал тесты для проверки работы upgrade

**Comment by kuzmichevdima** [comment]
Нужны еще тесты для проверки работы метода final_state (название поменять) у разных видов, а не только всего поля.

**Comment by befozg** [comment]
написал

**Comment by kuzmichevdima** [comment]
https://github.com/Karen-1999/Game-Life/blob/2b0e8ce20d7de00693dd63603424e4e6d6372b50/utest_model.py#L75

обращаться к внутреннему (как бы приватному) count_of_neighbors_dict извне - плохо, поскольку пользователь твоего класса не должен обращаться к приватным данным напрямую. Лучше сделать метод, который возвращает словарь, а сам словарь переименовать с _ в начале (так принято называть "приватные" аттрибуты)

**Comment by befozg** [comment]
исправил
